/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#4d6452",
        "on-primary": "#e4ffe7",
        "primary-container": "#cfe9d2",
        "on-primary-container": "#405746",
        "primary-dim": "#415846",
        "primary-fixed": "#cfe9d2",
        "primary-fixed-dim": "#c1dbc4",
        "secondary": "#715a4d",
        "on-secondary": "#fff7f5",
        "secondary-container": "#fcdccb",
        "on-secondary-container": "#634d40",
        "secondary-dim": "#654e42",
        "secondary-fixed": "#fcdccb",
        "secondary-fixed-dim": "#edcebe",
        "on-secondary-fixed": "#4f3b2f",
        "on-secondary-fixed-variant": "#6e574a",
        "tertiary": "#5f5f5f",
        "tertiary-dim": "#535353",
        "tertiary-container": "#f5f3f3",
        "tertiary-fixed": "#f5f3f3",
        "tertiary-fixed-dim": "#e6e5e5",
        "on-tertiary": "#faf8f8",
        "on-tertiary-fixed": "#494a4a",
        "on-tertiary-fixed-variant": "#666666",
        "on-tertiary-container": "#5b5c5c",
        "surface": "#fafaf5",
        "surface-dim": "#d5dcd0",
        "surface-bright": "#fafaf5",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4ee",
        "surface-container": "#ecefe7",
        "surface-container-high": "#e5eae0",
        "surface-container-highest": "#dee4da",
        "surface-variant": "#dee4da",
        "surface-tint": "#4d6452",
        "background": "#fafaf5",
        "on-surface": "#2e342d",
        "on-surface-variant": "#5a6159",
        "on-background": "#2e342d",
        "outline": "#767c74",
        "outline-variant": "#aeb4aa",
        "error": "#9f403d",
        "error-dim": "#4e0309",
        "error-container": "#fe8983",
        "on-error": "#fff7f6",
        "on-error-container": "#752121",
        "inverse-surface": "#0d0f0c",
        "inverse-on-surface": "#9c9d99",
        "inverse-primary": "#daf5dd",
        "on-primary-fixed": "#2e4434",
        "on-primary-fixed-variant": "#4a614f",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-in',
        'slide-up': 'slideUp 0.3s ease-out',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
